FROM centos:7

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm \
    && yum install -y puppet-agent \
    && yum clean all

ENTRYPOINT [ "/sbin/init" ]
